# Starter pipeline
- task: CmdLine@2
  inputs:
    script: |
      public class HelloWorld {
        public static void main(String[] args) {
           int num1 = 55, num2 = 15, sum,sub;
          sum = num1 + num2;
          sub = num1 - num2;
          System.out.println("Subtraction of 2 numbers: "+sub);
          System.out.println("Sum of these numbers: "+sum);
          System.out.println("Hello, World");
          System.out.println("Build, Test, Deploy");
          System.out.println("Hi klu");
          System.out.println("jenkins-Continuous Integration");
        }
      }
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
