# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
public class HelloWorld {
  public static void main(String[] args) {
     int num1 = 55, num2 = 15, sum,sub;
    sum = num1 + num2;
    sub = num1 - num2;
    System.out.println("Subtraction of 2 numbers: "+sub);
    System.out.println("Sum of these numbers: "+sum);
    System.out.println("Hello, World");
    System.out.println("Build, Test, Deploy");
    System.out.println("Hi klu");
    System.out.println("jenkins-Continuous Integration");
  }
}